[workspace]
release = false
release_always = false
changelog_update = false
pr_labels = ["release"]
max_analyze_commits = 2000

[[package]]
name = "use-path"
release = true
version_group = "rustuse-fs"

[[package]]
name = "use-file-name"
release = true
version_group = "rustuse-fs"

[[package]]
name = "use-extension"
release = true
version_group = "rustuse-fs"

[[package]]
name = "use-dir"
release = true
version_group = "rustuse-fs"

[[package]]
name = "use-file-stem"
release = true
version_group = "rustuse-fs"

[[package]]
name = "use-fs"
release = true
version_group = "rustuse-fs"
changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_include = [
  "use-path",
  "use-file-name",
  "use-extension",
  "use-dir",
  "use-file-stem",
]

[changelog]
header = """# Changelog

## Unreleased
"""
protect_breaking_commits = true
sort_commits = "oldest"
commit_parsers = [
  { message = "^feat(?:\\([^)]+\\))?!?: .+", group = "Added" },
  { message = "^fix(?:\\([^)]+\\))?!?: .+", group = "Fixed" },
  { message = "^security(?:\\([^)]+\\))?!?: .+", group = "Security" },
  { message = "^(?:refactor|perf|change)(?:\\([^)]+\\))?!?: .+", group = "Changed" },
  { message = "^docs(?:\\([^)]+\\))?!?: .+", group = "Documentation" },
  { message = "^(?:build|ci|chore|deps|test)(?:\\([^)]+\\))?!?: .+", group = "Tooling" },
  { footer = "^changelog: ?ignore$", skip = true },
  { message = "^.*", group = "Changed" },
]